version: '3'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    container_name: stock-tracker
    build:
      context: ./
      target: development
    image: stock-tracker
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      NODE_ENV: development
      DATABASE_HOST: db
      DB_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
      API_KEY: O4TQVO4WNT7KQK04
      SECRET: abc
    links:
      - db
    volumes:
      - './:/src'
  migration:
    image: stock-tracker:latest
    command: ["npm", "run", "migration:up"]
    environment:
      NODE_ENV: development
      DATABASE_HOST: db
      DB_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
    links:
      - db
    depends_on:
      - db
volumes:
  db:
    driver: local
